### ISSUE TITLE
Don't allow "-" in crud generator for path

### ISSUE THREAD

**Issue by apsylone** [sensiolabs/SensioGeneratorBundle#146]
When generating CRUD with command tool, char "-" is allowed while Symfony 2.1 routing system don't allow "-" as separator for route name.

Example of route name : 
"project-type" >> generate Exception
"project_type" >> is OK

**Comment by javiereguiluz** [comment]
I'm closing this old issue as "fixed". I've tested it using `project-type` as the route prefix. Generated routes and controllers use `project-route_...` as the route name, but everything works right in Symfony 2.3 or higher:

```yaml
project-type:
    path:     /
    defaults: { _controller: "AppBundle:Post:index" }

project-type_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Post:show" }

# ...
```

```php
public function createAction(Request $request)
{
    // ...

    if ($form->isValid()) {
        $em = $this->getDoctrine()->getManager();
        $em->persist($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('project-type_show', array(
            'id' => $entity->getId())
        ));
    }

    // ...
}
```
