### ISSUE TITLE
Improving the keys used to import bundles' routes

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs/SensioGeneratorBundle#313]
When generating bundles, you can automatically import their routes from the `app/config/routing.yml`. This is an example of this file after generating three random bundles called FooBarBundle, Acme/ApiNonSharedBundle and Acme/ApiBundle:

```yaml
foo_bar:
    resource: "@FooBarBundle/Controller/"
    type:     annotation
    prefix:   /

acme_api_non_shared:
    resource: "@AcmeApiNonSharedBundle/Resources/config/routing.xml"
    prefix:   /

acme_api:
    resource: "@AcmeApiBundle/Resources/config/routing.xml"
    prefix:   /
```

Thanks to [this line of code of the Routing Manipulator](https://github.com/sensiolabs/SensioGeneratorBundle/blob/master/Manipulator/RoutingManipulator.php#L50), the key used to import the routes doesn't contain the `bundle` suffix.

The problem is that now we can generate bundles without a vendor. So if someone generates a `UserBundle`, they key would be `user`, which seems too generic and it could cause collisions.

Given that this key is useless for developers, could we re-add the `bundle` suffix or add a `_` prefix or something like that to avoid potential problems?

**With the suffix**

```yaml
foo_bar_bundle:
    resource: "@FooBarBundle/Controller/"
    type:     annotation
    prefix:   /

acme_api_non_shared_bundle:
    resource: "@AcmeApiNonSharedBundle/Resources/config/routing.xml"
    prefix:   /

acme_api_bundle:
    resource: "@AcmeApiBundle/Resources/config/routing.xml"
    prefix:   /
```

**With the prefix**

```yaml
_foo_bar:
    resource: "@FooBarBundle/Controller/"
    type:     annotation
    prefix:   /

_acme_api_non_shared:
    resource: "@AcmeApiNonSharedBundle/Resources/config/routing.xml"
    prefix:   /

_acme_api:
    resource: "@AcmeApiBundle/Resources/config/routing.xml"
    prefix:   /
```
