### ISSUE TITLE
Is there a way to generate forms from entities declared outside of a bundle ?

### ISSUE THREAD

**Issue by paztek** [sensiolabs/SensioGeneratorBundle#323]
I declared my model outside of my bundles under the Paztek\Entity namespace and now I'm trying to generate a FormType for one of my entities.

Here is my mapping in my ```config.yml```file:
```
doctrine:
    ...
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
                paztek:
                        type: annotation
                        is_bundle: false
                        dir: %kernel.root_dir%/../src/Paztek/Entity
                        alias: "core"
                        prefix: Paztek\Entity

```
The command ```doctrine:generate:form core:MyEntity``` fails with:
```
Bundle "core" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file?
```

I tried omitting the "core", giving the fully qualified name of my entity, etc... but this is the closest I can get.

Any idea if this is possible at all and how to do it ?
