### ISSUE TITLE
DoctrineEntityGenerator fails for entities outside bundles

### ISSUE THREAD

**Issue by davidgorges** [sensiolabs/SensioGeneratorBundle#335]
DoctrineEntityGenerator tries to get a bundle from the shortcut notation but doesn't check whether the entity is inside a bundle or not.

e.g.:

``` yaml
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
          CustomEntity:
            mapping: true
            type: annotation
            dir: %kernel.root_dir%/../src/Custom/Model/
            prefix: Custom\Model
            alias: Custom
            is_bundle: false
```

```
php app/console generate:doctrine:form Custom:State
```

raises an error:

```
[InvalidArgumentException]
 Bundle "Custom" does not exist or it is not enabled. Maybe you forgot to add it in the 
 registerBundles() method of your AppKernel.php file
```
