### ISSUE TITLE
Methods are created multiple times if they're used in multiple lifecycleCallbacks

### ISSUE THREAD

**Issue by robinkanters** [sensiolabs/SensioGeneratorBundle#470]
So I defined an entity with this lifecycleCallback config:

```yaml
AppBundle\Entity\Money:
    type: entity
    table: null
    lifecycleCallbacks:
        preUpdate: [ updateUpdatedAt ]
        prePersist: [ updateCreatedAt, updateUpdatedAt ]
```

Upon running `doctrine:generate:entities AppBundle`, I got a `Money` class with 2 `updateUpdatedAt` methods, which is obviously invalid.
