### ISSUE TITLE
[Proposal] GenerateServiceCommand

### ISSUE THREAD

**Issue by skafandri** [sensiolabs/SensioGeneratorBundle#529]
The command would look like:
````
php console generate:service app.incoiver AppBundle\\Service
````
If *yaml* is used, it would append to the services section in config:
````yaml
app.service:
        class: AppBundle\Service
        arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher']
        calls: ['setLogger', ['@logger']]
````
Given a class definition:
````php
class Service
{
    public function __construct(EntityManager $entityManager, EventDispatcherInterface $eventDispatcher)
    {
    }
    public function setLogger(LoggerInterface $logger)
    {
    }
}
````

If the idea sounds interesting, we can agree on an initial set of options and arguments and start a WIP.
